{{- if .Values.externalSecret.enabled }}
{{- range .Values.externalSecret.secrets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  labels: {{- include "retail.labels" $ | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ $.Values.externalSecret.secretStore.name }}
    kind: {{ $.Values.externalSecret.secretStore.kind }}
  target:
    name: {{ .name }}
  data:
    {{- range .data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteKey }}
        property: {{ .property }}
    {{- end }}
{{- end }}
{{- end }}
